version: "3.9"

services:

  web-app:
    image: web-app
    restart: always
    container_name: web-app
    pull_policy: build
    build: .
    ports:
      - "9090:8080"
    environment:
      GIN_MODE: ${GIN_MODE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 2
